Algoritmo "Operadores Lógicos"

Var
   a, b, c: inteiro
Inicio
   a <- 2
   b <- 3
   c <- 5

   Escreval ("Uma siutação é verdadeira e falsa? ")
   Escreval (verdadeiro e falso)
   Escreval ("---------------------")

   Escreval ("a é igual a b ou c é maior que a? ")
   Escreval ((a=b) ou (c>a))
   Escreval ("---------------------")
   
   Escreval ("a não é igual a b ou c é maior que a? ")
   Escreval (nao((a=b) ou (c>a)))
   Escreval ("---------------------")

Fimalgoritmo