Algoritmo "Exercícios de algoritimos"

Var
   ano_atual, ano_nascimento, idade: inteiro

Inicio
   Escreval ("Em que anos nós estamos? ")
   Leia (ano_atual)
   Escreval ("************************")
   Escreval ("Em que ano eu nasci? ")
   Leia (ano_nascimento)
   Escreval ("************************")
   idade <- (ano_atual - ano_nascimento)
   Escreval ("Minha idade é ", idade)
   Escreval ("************************")
Fimalgoritmo